POST http://localhost:8000/api/v1/createPoll/
Content-Type: application/json

{
    "title": "Какой покемон лучше?",
    "description": "Выберите лучшего покемона",
    "choices": [
        {
            "choice_text": "пичу"
        },
        {
            "choice_text": "черманде"
        },
        {
            "choice_text": "минью"
        }
    ]
}

###
