POST http://localhost:8000/api/v1/createPoll/
Content-Type: application/json

{
    "title": "Какой покемон лучше?",
    "description": "Выберите лучшего покемона",
    "choices": [
        {
            "choice_text": "пичу"
        },
        {
            "choice_text": "черманде"
        },
        {
            "choice_text": "минью"
        }
    ]
}

###

PATCH http://localhost:8000/api/v1/poll/1/
Content-Type: application/json

{
    "choice_id": 2
}

###

GET http://localhost:8000/api/v1/poll/
Content-Type: application/json

###

GET http://localhost:8000/api/v1/getResult/1/
Content-Type: application/json
